apiVersion: v1
kind: Namespace
metadata:
  name: educrm-production
  labels:
    name: educrm-production
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: educrm-staging
  labels:
    name: educrm-staging
    environment: staging
